version: '3'

services:
        openhab:
                build: openhab
                ports:
                        - "443:8443"
                networks:
                        - openhab_mqtt
                volumes:
                        - "/etc/localtime:/etc/localtime:ro"
                        - "/etc/timezone:/etc/timezone:ro"
                        - "./data/openhab/addons:/openhab/addons"
                        - "./data/openhab/conf:/openhab/conf"
                        - "./data/openhab/userdata:/openhab/userdata"
                environment:
                        #OPENHAB_HTTP_PORT: "8080"
                        OPENHAB_HTTPS_PORT: "8443"
                        USER_ID: "1000"
                        GROUP_ID: "1000"

        mqtt:
                image:
                        eclipse-mosquitto:latest
                networks:
                        - openhab_mqtt

        zigbee2mqtt:
                build: zigbee2mqtt
                volumes:
                        - ./data/zigbee2mqtt:/app/data
                        - /run/udev:/run/udev:ro
                devices:
                        - /dev/ttyACM0:/dev/ttyACM0
                networks:
                        - openhab_mqtt
                privileged: true
                environment:
                        - TZ=Europe/Paris

        zigbee2mqttAssistant:
                image: carldebilly/zigbee2mqttassistant
                networks:
                        - openhab_mqtt
                environment:
                        - Z2MA_SETTINGS__MQTTSERVER=mqtt
                        - TZ=Europe/Paris
                ports:
                        - 8880:80
                restart: unless-stopped


        broadlink-mqtt:
                image: dmitriy/broadlink-mqtt
                networks:
                        - openhab_mqtt
                volumes:
                        - "./data/broadlink:/app/commands"
                environment:
                        - MQTT_SERVER=mqtt
                        - MQTT_TOPIC_PREFIX=broadlink/rm-mini3/
                        - DEVICE_HOST=192.168.1.12
                        - DEVICE_MAC=24:df:a7:7b:12:77

networks:
        openhab_mqtt:
