version: '3'

services:

        portainer:
                image: portainer/portainer
                command: -H unix:///var/run/docker.sock
                restart: always
                ports:
                        - 9000:9000
                        - 8000:8000
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock

        openhab:
                build: openhab
                ports:
                        - "443:8443"
                networks:
                        - openhab_mqtt
                volumes:
                        - "/etc/localtime:/etc/localtime:ro"
                        - "/etc/timezone:/etc/timezone:ro"
                        - "./data/openhab/addons:/openhab/addons"
                        - "./data/openhab/conf:/openhab/conf"
                        - "./data/openhab/userdata:/openhab/userdata"
                environment:
                        #OPENHAB_HTTP_PORT: "8080"
                        OPENHAB_HTTPS_PORT: "8443"
                        USER_ID: "1000"
                        GROUP_ID: "1000"

        mqtt:
                image:
                        eclipse-mosquitto:latest
                networks:
                        - openhab_mqtt

        zigbee2mqtt:
                container_name: zigbee2mqtt
                image: koenkk/zigbee2mqtt
                volumes:
                        - ./data:/app/data
                        - /run/udev:/run/udev:ro
                devices:
                        - /dev/ttyACM0:/dev/ttyACM0
                networks:
                        - openhab_mqtt
                privileged: true
                environment:
                        - TZ=Europe/Paris

        samba:
                image:
                        dperson/samba:latest
                ports:
                        - "139:139"
                        - "445:445"
                network_mode: "host"
                volumes:
                        - "./data:/data/openhab"
                environment:
                        NMBD: 'yes'
                        WORKGROUP: 'OPENHAB'
                        USER: 'test;1234;1000;test;1000'
                        SHARE: 'OpenHAB;/data/openhab'
                        #PERMISSIONS: 'yes'
        
        rclone_rclone:
                image: rclone/rclone
                container_name: rclone_rclone
                command: rcd --rc-web-gui --rc-addr :5572 --rc-user toto --rc-pass 1234
                ports:
                        - "5572:5572"
                volumes:
                        - ./data/rclone:/config/rclone
                        - ./data/rclone:/logs
                environment:
                        - PHP_TZ=Europe/Paris
                        - PUID=1000
                        - PGID=1000


networks:
        openhab_mqtt:
