FROM openhab/openhab:3.0.0

COPY addons.cfg /openhab/dist/conf/services/addons.cfg
COPY addons.cfg /openhab/conf/services/addons.cfg

COPY things /openhab/dist/conf/things
COPY things /openhab/conf/things
